### ISSUE TITLE
Chapter 8: error on ecommerce app

### ISSUE THREAD

**Issue by carloscrovara** [PacktPublishing/React-Native-Blueprints#4] opened 2017-12-18 17:52 UTC
I have an issue with the ecommerce app (chapter 8): 

On the Android app the button of "Confirm purchase" didn´t work.

**Comment by emilioicai** [comment] 2018-07-05 09:02
@carloscrovara can you provide more information please? I cannot reproduce in my local environment

**Comment by sohamapackt** [comment] 2020-10-22 07:03
Hi,

I am closing this issue. If the issue still persists, feel free to reopen it.
Thanks!

**Closed by sohamapackt** 2020-10-22 07:03 UTC
